### ISSUE TITLE
cannot activate plugin on wordpress - fatal error

### ISSUE THREAD

**Issue by okielokie** [archetyped/cornerstone#50] opened 2021-04-22 16:08 UTC
Hello,

I got this error when trying to activate the plugin:

Fatal error: Uncaught Error: Call to undefined method ReflectionType::getName() in /home/customer/www/viktoriyaandoksana.com/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php:106 Stack trace: #0 [internal function]: Themeco\Cornerstone\Plugin->Themeco\Cornerstone\{closure}(Object(ReflectionParameter)) #1 /home/customer/www/viktoriyaandoksana.com/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(117): array_map(Object(Closure), Array) #2 /home/customer/www/viktoriyaandoksana.com/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(137): Themeco\Cornerstone\Plugin->create('\\Themeco\\Corner...') #3 /home/customer/www/viktoriyaandoksana.com/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(73): Themeco\Cornerstone\Plugin->resolve('\\Themeco\\Corner...') #4 /home/customer/www/viktoriyaandoksana.com/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(44): Themeco\Cornerstone\Plugin->setup_services('is_admin') #5 /home/customer/w in /home/customer/www/viktoriyaandoksana.com/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php on line 106

could you please advice?

**Comment by archetyped** [comment] 2021-04-23 03:24
Duplicate of #49

**Closed by archetyped** 2021-04-23 03:24 UTC
